package server

import (
	"net/http"
	_ "jiyue.im/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gin-gonic/gin"
	"jiyue.im/pkg/auth"
	"jiyue.im/server/middleware"
	"jiyue.im/service"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

func LoadRouter(mw ...gin.HandlerFunc) *gin.Engine {
	g := gin.New()

	if gin.Mode() == "debug" {
		g.Use(gin.Logger())
	}
	g.Use(gin.Recovery())
	g.Use(mw...)

	// 404 Handler.
	g.NoRoute(func(c *gin.Context) {
		c.JSON(http.StatusNotFound, gin.H{
			"你访问的页面不存在": "XXXXXXXXXXXXXXXXX",
		})
	})

	g.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	ping(g)

	u := g.Group("/v1/user")
	{
		u.POST("/register", service.UserRegister)
		u.POST("/token", service.GetToken)
	}

	g.POST("/v1/token/verify", middleware.AuthMiddleware(auth.USER), service.VerifyToken)

	classic := g.Group("/v1/classic")
	classic.Use(middleware.AuthMiddleware(auth.USER))
	{
		classic.GET("/latest", service.GetLatest)
	}

	return g
}

func ping(g *gin.Engine) {
	g.GET("/ping", service.HealthCheck)
}
