basePath: '{{.BasePath}}'
definitions:
  model.CreateResponse:
    properties:
      id:
        type: integer
      nickname:
        type: string
    type: object
  model.ParamFavorReq:
    properties:
      id:
        type: integer
      type:
        type: integer
    required:
    - id
    - type
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    required:
    - email
    - nickname
    - password
    type: object
  model.Token:
    properties:
      token:
        type: string
    type: object
  model.TokenRequest:
    properties:
      account:
        type: string
      secret:
        type: string
      type:
        type: integer
    required:
    - account
    type: object
  service.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /v1/classic/detail/{type}/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: Type
        in: path
        name: type
        required: true
        type: integer
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '[{"id": 1,"image": "images/music.7.png","content": "无人问我粥可温
            风雨不见江湖人", "title": "月之门《枫华谷的枫林》","fav_nums": 145,"type": 200,"url": "http://music.163.com/song/media/outer/url?id=393926.mp3"}]'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 获取期刊详情
      tags:
      - Classic
  /v1/classic/favor/{type}/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: Type
        in: path
        name: type
        required: true
        type: integer
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '[{"id": 1,"image": "images/music.7.png","content": "无人问我粥可温
            风雨不见江湖人", "title": "月之门《枫华谷的枫林》","fav_nums": 145,"type": 200,"url": "http://music.163.com/song/media/outer/url?id=393926.mp3"}]'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 用户是否喜欢一个期刊
      tags:
      - Classic
  /v1/classic/favors:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"content": "人生不能像做菜，把所有的料准备好才下锅","favnums": 0,"id": 7,"image":
            "images/movie.8.png","index": 8,"like_status": true,"pubdate": "2019-04-05T17:12:04+08:00","title":
            "李安《饮食男女 》","type": 100}'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 获取用户喜欢的期刊
      tags:
      - Classic
  /v1/classic/latest:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"content": "人生不能像做菜，把所有的料准备好才下锅","favnums": 0,"id": 7,"image":
            "images/movie.8.png","index": 8,"like_status": true,"pubdate": "2019-04-05T17:12:04+08:00","title":
            "李安《饮食男女 》","type": 100}'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 获取最新期刊
      tags:
      - Classic
  /v1/classic/next/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 获取当前期刊的下一个期刊
      tags:
      - Classic
  /v1/classic/previous/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 获取当前期刊的上一个期刊
      tags:
      - Classic
  /v1/like/:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: likeParam
        in: body
        name: likeParam
        required: true
        schema:
          $ref: '#/definitions/model.ParamFavorReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 期刊点赞
      tags:
      - Like
  /v1/like/cancel:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      - description: likeParam
        in: body
        name: likeParam
        required: true
        schema:
          $ref: '#/definitions/model.ParamFavorReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 期刊取消点赞
      tags:
      - Like
  /v1/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱方式注册用户
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CreateResponse'
            type: object
      summary: 邮箱方式注册用户
      tags:
      - User
  /v1/user/token:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/model.TokenRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Njc3Njk4MDYsImlhdCI6MTU2Nzc2MjYwNiwiaWQiOjEsIm5iZiI6MTU2Nzc2MjYwNiwic2NvcGUiOjh9.-VlL6oAa8mMD2Wd0Os1in1V5T9sdcwv6OCupihZKZNY"}'
          schema:
            $ref: '#/definitions/model.Token'
            type: object
      summary: 获取token
      tags:
      - User
  /v1/user/token/verify:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-auth-token
        in: header
        name: x-auth-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response'
            type: object
      summary: 验证Token合法性
      tags:
      - User
swagger: "2.0"
